/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package beltran;

import beltran.Clases.ServicioLogin.SessionManager;
import javax.swing.JOptionPane;

/**
 *
 * @author julia
 */
public class Administracion extends javax.swing.JFrame {

    /**
     * Creates new form Administracion
     */
    public Administracion() {
        initComponents();
                verificarSesion(); // Verifica la sesión al iniciar el frame
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    }

 private void verificarSesion() {
        // Asumiendo que SessionManager.isLoggedIn es el estado de inicio de sesión
        if (!SessionManager.isLoggedIn) {
            // Mostrar un mensaje de advertencia al usuario
            JOptionPane.showMessageDialog(this, 
                "Debes iniciar sesión para acceder a esta sección.", 
                "Acceso Denegado", 
                JOptionPane.WARNING_MESSAGE);

            // Redirigir al inicio de sesión
            new InicioSesion().setVisible(true);
            // Cerrar la ventana actual (Administracion)
            this.dispose();
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        openRegistroAlumnos = new javax.swing.JButton();
        btnBuscador = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        openRegistroAlumnos.setText("Registro Alumno");
        openRegistroAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openRegistroAlumnosActionPerformed(evt);
            }
        });

        btnBuscador.setText("Buscar Alumno");
        btnBuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(openRegistroAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(257, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(openRegistroAlumnos)
                .addGap(18, 18, 18)
                .addComponent(btnBuscador)
                .addContainerGap(173, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openRegistroAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openRegistroAlumnosActionPerformed
  // Método para abrir la ventana RegistroAlumnos
        RegistroALumnos registro = new RegistroALumnos(this);
        registro.setVisible(true);
        // Ocultar la ventana Administracion
        this.setVisible(false);    }//GEN-LAST:event_openRegistroAlumnosActionPerformed

    private void btnBuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscadorActionPerformed
               // Crear e inicializar el frame BuscadorAlumnos
        BuscadorAlumnos buscadorAlumnos = new BuscadorAlumnos();
        buscadorAlumnos.setVisible(true); // Mostrar el frame
    }//GEN-LAST:event_btnBuscadorActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscador;
    private javax.swing.JButton openRegistroAlumnos;
    // End of variables declaration//GEN-END:variables
}
